install.packages("data.table")
install.packages("ggplot2")
install.packages("optparse")
install.packages("stringr")
install.packages("lubridate")
install.packages("rvest")
install.packages("jsonlite")
